apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: grafana-
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      # affinity will be set accordingly by the server
      containers:
      - name: grafana
        image: grafana/grafana:11.1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
